# Generated by Django 5.2.10 on 2026-02-03 18:05

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Bank short code (e.g., SBI, HDFC)",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(help_text="Full bank name", max_length=255)),
                (
                    "ifsc_pattern",
                    models.CharField(
                        blank=True,
                        help_text="IFSC code pattern (e.g., SBIN for SBI)",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banks",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bank",
                "verbose_name_plural": "Banks",
                "db_table": "masters_bank",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["organization", "is_active"],
                        name="masters_ban_organiz_8774a2_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "code"),
                        name="unique_organization_bank_code",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="GstRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique code (e.g., GST18, GST5)",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Description (e.g., Standard 18%, Essential 5%)",
                        max_length=255,
                    ),
                ),
                (
                    "cgst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Central GST rate percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "sgst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="State GST rate percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "igst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Integrated GST rate percentage (for inter-state)",
                        max_digits=5,
                    ),
                ),
                (
                    "hsn_code",
                    models.CharField(
                        blank=True,
                        help_text="HSN/SAC code (e.g., 996721 for storage services)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the default GST rate for the organization?",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gst_rates",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "GST Rate",
                "verbose_name_plural": "GST Rates",
                "db_table": "masters_gst_rate",
                "ordering": ["code"],
                "indexes": [
                    models.Index(
                        fields=["organization", "is_active"],
                        name="masters_gst_organiz_36f150_idx",
                    ),
                    models.Index(
                        fields=["organization", "is_default"],
                        name="masters_gst_organiz_c78f1e_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "code"),
                        name="unique_organization_gst_rate_code",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LaborRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("LOADING", "Loading"),
                            ("UNLOADING", "Unloading"),
                            ("KATAI", "Katai (Cutting)"),
                            ("RELOAD", "Reload"),
                            ("DUMP", "Dump"),
                            ("DALA", "Dala"),
                        ],
                        help_text="Type of labor rate",
                        max_length=20,
                    ),
                ),
                (
                    "packet_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PKT1", "Packet Type 1"),
                            ("PKT2", "Packet Type 2"),
                            ("PKT3", "Packet Type 3"),
                        ],
                        help_text="Packet type (null for flat rates)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Rate per unit",
                        max_digits=10,
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        help_text="Date from which this rate is effective"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labor_rates",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Labor Rate",
                "verbose_name_plural": "Labor Rates",
                "db_table": "masters_labor_rate",
                "ordering": ["-effective_from", "rate_type"],
                "indexes": [
                    models.Index(
                        fields=["organization", "rate_type"],
                        name="masters_lab_organiz_964b86_idx",
                    ),
                    models.Index(
                        fields=["organization", "is_active"],
                        name="masters_lab_organiz_1551bd_idx",
                    ),
                    models.Index(
                        fields=["organization", "effective_from"],
                        name="masters_lab_organiz_8e6937_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "organization",
                            "rate_type",
                            "packet_type",
                            "effective_from",
                        ),
                        name="unique_organization_labor_rate",
                    )
                ],
            },
        ),
    ]
