# Generated by Django 5.2.10 on 2026-02-03 13:10

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commodity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(max_length=255)),
                ("name_hindi", models.CharField(blank=True, max_length=255, null=True)),
                ("variety", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "grace_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of grace days before rent starts"
                    ),
                ),
                (
                    "default_rent_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Default rent rate per quintal per month",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commodities",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "commodity",
                "verbose_name_plural": "commodities",
                "db_table": "inventory_commodity",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Amad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amad_no",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated: YYYY-NNNNN",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "pkt1",
                    models.PositiveIntegerField(
                        default=0, help_text="Packet count - Type 1 (e.g., large bags)"
                    ),
                ),
                (
                    "pwt1",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total weight for Type 1 packets (kg)",
                        max_digits=10,
                    ),
                ),
                (
                    "pkt2",
                    models.PositiveIntegerField(
                        default=0, help_text="Packet count - Type 2 (e.g., medium bags)"
                    ),
                ),
                (
                    "pwt2",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total weight for Type 2 packets (kg)",
                        max_digits=10,
                    ),
                ),
                (
                    "pkt3",
                    models.PositiveIntegerField(
                        default=0, help_text="Packet count - Type 3 (e.g., small bags)"
                    ),
                ),
                (
                    "pwt3",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total weight for Type 3 packets (kg)",
                        max_digits=10,
                    ),
                ),
                ("total_packets", models.PositiveIntegerField(default=0)),
                (
                    "total_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total weight in kg",
                        max_digits=12,
                    ),
                ),
                (
                    "marks",
                    models.CharField(
                        blank=True,
                        help_text="Identification marks on packets",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "grace_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Grace days before rent starts (from commodity or overridden)",
                    ),
                ),
                (
                    "rent_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Rent rate per quintal per month",
                        max_digits=10,
                    ),
                ),
                (
                    "amad_type",
                    models.CharField(
                        choices=[("SEEDHI", "Seedhi (Direct)"), ("DUMP", "Dump")],
                        default="SEEDHI",
                        max_length=10,
                    ),
                ),
                ("e_way_bill", models.CharField(blank=True, max_length=50, null=True)),
                ("is_fully_dispatched", models.BooleanField(default=False)),
                ("remaining_packets", models.PositiveIntegerField(default=0)),
                (
                    "remaining_weight",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amads",
                        to="authentication.organization",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        help_text="Party account (depositor)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="amads",
                        to="accounting.account",
                    ),
                ),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="amads",
                        to="inventory.commodity",
                    ),
                ),
            ],
            options={
                "verbose_name": "amad",
                "verbose_name_plural": "amads",
                "db_table": "inventory_amad",
                "ordering": ["-date", "-amad_no"],
            },
        ),
        migrations.CreateModel(
            name="Rent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "serial_no",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated serial number",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "receiver_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of person receiving goods (if different from party)",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("packets", models.PositiveIntegerField(default=0)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Weight in kg",
                        max_digits=12,
                    ),
                ),
                (
                    "storage_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of days goods were stored"
                    ),
                ),
                (
                    "rent_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Rent rate per quintal per month",
                        max_digits=10,
                    ),
                ),
                (
                    "rent_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "gst_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("18.00"), max_digits=5
                    ),
                ),
                (
                    "gst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "nikasi_type",
                    models.CharField(
                        choices=[
                            ("SEEDHI", "Seedhi (Direct)"),
                            ("KATAI", "Katai (Cut)"),
                        ],
                        default="SEEDHI",
                        max_length=10,
                    ),
                ),
                ("vehicle_no", models.CharField(blank=True, max_length=20, null=True)),
                ("narration", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amad",
                    models.ForeignKey(
                        help_text="Primary source Amad",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rents",
                        to="inventory.amad",
                    ),
                ),
                (
                    "ledger_entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated ledger entry for rent charge",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rent_entries",
                        to="accounting.partyledger",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rents",
                        to="authentication.organization",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        help_text="Original depositor party",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rents_as_depositor",
                        to="accounting.account",
                    ),
                ),
                (
                    "receiver_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Receiver account for stock transfers",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rents_as_receiver",
                        to="accounting.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "rent",
                "verbose_name_plural": "rents",
                "db_table": "inventory_rent",
                "ordering": ["-date", "-serial_no"],
            },
        ),
        migrations.CreateModel(
            name="AmadNikasi",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("packets_dispatched", models.PositiveIntegerField(default=0)),
                (
                    "weight_dispatched",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_links",
                        to="inventory.amad",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amad_nikasis",
                        to="authentication.organization",
                    ),
                ),
                (
                    "rent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_amads",
                        to="inventory.rent",
                    ),
                ),
            ],
            options={
                "verbose_name": "amad nikasi link",
                "verbose_name_plural": "amad nikasi links",
                "db_table": "inventory_amad_nikasi",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "capacity_quintals",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Room capacity in quintals",
                        max_digits=10,
                    ),
                ),
                (
                    "floor_count",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Number of floors in this room"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "room",
                "verbose_name_plural": "rooms",
                "db_table": "inventory_room",
                "ordering": ["number"],
            },
        ),
        migrations.AddField(
            model_name="amad",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="amads",
                to="inventory.room",
            ),
        ),
        migrations.CreateModel(
            name="Takpatti",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "takpatti_no",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated takpatti number",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("packets", models.PositiveIntegerField(default=0)),
                (
                    "gross_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Gross weight in kg",
                        max_digits=12,
                    ),
                ),
                (
                    "tare_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Tare weight (container/bag weight) in kg",
                        max_digits=12,
                    ),
                ),
                (
                    "net_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Net weight in kg",
                        max_digits=12,
                    ),
                ),
                (
                    "floor_no",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Floor number within the room"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="takpattis",
                        to="inventory.amad",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="takpattis",
                        to="authentication.organization",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="takpattis",
                        to="inventory.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "takpatti",
                "verbose_name_plural": "takpattis",
                "db_table": "inventory_takpatti",
                "ordering": ["-date", "-takpatti_no"],
            },
        ),
        migrations.CreateModel(
            name="Village",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(max_length=255)),
                ("name_hindi", models.CharField(blank=True, max_length=255, null=True)),
                ("post", models.CharField(blank=True, max_length=255, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="villages",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "village",
                "verbose_name_plural": "villages",
                "db_table": "inventory_village",
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="amad",
            name="village",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="amads",
                to="inventory.village",
            ),
        ),
        migrations.AddIndex(
            model_name="commodity",
            index=models.Index(
                fields=["organization", "is_active"],
                name="inventory_c_organiz_17edef_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="commodity",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"),
                name="unique_organization_commodity_code",
            ),
        ),
        migrations.AddIndex(
            model_name="rent",
            index=models.Index(
                fields=["organization", "date"], name="inventory_r_organiz_26fed9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rent",
            index=models.Index(
                fields=["organization", "party"], name="inventory_r_organiz_16815e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rent",
            index=models.Index(fields=["amad"], name="inventory_r_amad_id_aaf25a_idx"),
        ),
        migrations.AddConstraint(
            model_name="rent",
            constraint=models.UniqueConstraint(
                fields=("organization", "serial_no"),
                name="unique_organization_rent_serial_no",
            ),
        ),
        migrations.AddIndex(
            model_name="amadnikasi",
            index=models.Index(
                fields=["organization"], name="inventory_a_organiz_ed43cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="amadnikasi",
            index=models.Index(fields=["amad"], name="inventory_a_amad_id_3a0aa4_idx"),
        ),
        migrations.AddIndex(
            model_name="amadnikasi",
            index=models.Index(fields=["rent"], name="inventory_a_rent_id_73d471_idx"),
        ),
        migrations.AddConstraint(
            model_name="amadnikasi",
            constraint=models.UniqueConstraint(
                fields=("amad", "rent"), name="unique_amad_rent_link"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["organization", "is_active"],
                name="inventory_r_organiz_c54216_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("organization", "number"),
                name="unique_organization_room_number",
            ),
        ),
        migrations.AddIndex(
            model_name="takpatti",
            index=models.Index(
                fields=["organization", "date"], name="inventory_t_organiz_096878_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="takpatti",
            index=models.Index(fields=["amad"], name="inventory_t_amad_id_bfa84e_idx"),
        ),
        migrations.AddConstraint(
            model_name="takpatti",
            constraint=models.UniqueConstraint(
                fields=("organization", "takpatti_no"),
                name="unique_organization_takpatti_no",
            ),
        ),
        migrations.AddIndex(
            model_name="village",
            index=models.Index(
                fields=["organization", "is_active"],
                name="inventory_v_organiz_9ca130_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="village",
            index=models.Index(
                fields=["organization", "district"],
                name="inventory_v_organiz_d54fe2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="village",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="unique_organization_village_code"
            ),
        ),
        migrations.AddIndex(
            model_name="amad",
            index=models.Index(
                fields=["organization", "date"], name="inventory_a_organiz_ec431c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="amad",
            index=models.Index(
                fields=["organization", "party"], name="inventory_a_organiz_b33b16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="amad",
            index=models.Index(
                fields=["organization", "is_fully_dispatched"],
                name="inventory_a_organiz_c3b83f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="amad",
            index=models.Index(
                fields=["party", "is_fully_dispatched"],
                name="inventory_a_party_i_1fe778_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="amad",
            constraint=models.UniqueConstraint(
                fields=("organization", "amad_no"), name="unique_organization_amad_no"
            ),
        ),
    ]
