# Generated by Django 5.2.10 on 2026-02-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_sugar_free",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if this room is for sugar-free storage",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="occupancy_color",
            field=models.CharField(
                blank=True,
                help_text="Color code for visual map display (e.g., #4CAF50)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="rack_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Total number of racks in this room"
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="racks_per_row",
            field=models.PositiveIntegerField(
                default=10, help_text="Number of racks per row for grid display"
            ),
        ),
    ]
