# Generated by Django 5.2.10 on 2026-02-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_room_is_sugar_free_room_occupancy_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="max_temperature",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum allowed temperature in Celsius",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="min_temperature",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum allowed temperature in Celsius",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="name_hindi",
            field=models.CharField(
                blank=True, help_text="Room name in Hindi", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="target_temperature",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Target temperature in Celsius",
                max_digits=5,
                null=True,
            ),
        ),
    ]
