# Generated by Django 5.2.10 on 2026-02-06 19:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_organizationmembership_backdate_entry_limit_and_more"),
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SequenceConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=30)),
                ("label", models.CharField(max_length=100)),
                ("prefix", models.CharField(blank=True, default="", max_length=10)),
                ("separator", models.CharField(default="/", max_length=5)),
                ("include_year", models.BooleanField(default=True)),
                ("padding", models.PositiveIntegerField(default=5)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequence_configs",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "sequence config",
                "verbose_name_plural": "sequence configs",
                "db_table": "system_sequence_config",
                "ordering": ["key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "key"),
                        name="unique_sequence_config_per_org",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SequenceCounter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=30)),
                ("year", models.PositiveIntegerField()),
                ("last_number", models.PositiveIntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sequence_counters",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "sequence counter",
                "verbose_name_plural": "sequence counters",
                "db_table": "system_sequence_counter",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "key", "year"),
                        name="unique_sequence_counter_per_org_key_year",
                    )
                ],
            },
        ),
    ]
