# Generated by Django 5.2.10 on 2026-02-05 19:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("authentication", "0002_organizationmembership_backdate_entry_limit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BardanaIssueHeader",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "voucher_no",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated: BI/YYYY-NNNNN",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("party_name", models.CharField(max_length=255)),
                ("total_qty", models.PositiveIntegerField(default=0)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                ("is_advance", models.BooleanField(default=False)),
                (
                    "interest_rate_pm",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monthly interest rate percentage",
                        max_digits=5,
                    ),
                ),
                ("expected_arrival_date", models.DateField(blank=True, null=True)),
                ("expected_bags", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "reference_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_bardana_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_bardana_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ledger_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bardana_issue_entries",
                        to="accounting.partyledger",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bardana_issues",
                        to="authentication.organization",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bardana_issues",
                        to="accounting.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bardana Issue",
                "verbose_name_plural": "Bardana Issues",
                "db_table": "bardana_issue_header",
                "ordering": ["-date", "-voucher_no"],
            },
        ),
        migrations.CreateModel(
            name="BardanaReturnHeader",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "voucher_no",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated: BR/YYYY-NNNNN",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("party_name", models.CharField(max_length=255)),
                ("total_qty", models.PositiveIntegerField(default=0)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_bardana_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_bardana_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ledger_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bardana_return_entries",
                        to="accounting.partyledger",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bardana_returns",
                        to="authentication.organization",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bardana_returns",
                        to="accounting.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bardana Return",
                "verbose_name_plural": "Bardana Returns",
                "db_table": "bardana_return_header",
                "ordering": ["-date", "-voucher_no"],
            },
        ),
        migrations.CreateModel(
            name="BardanaType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(max_length=100)),
                (
                    "rate_per_unit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("opening_stock", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bardana_types",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bardana Type",
                "verbose_name_plural": "Bardana Types",
                "db_table": "bardana_type",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="BardanaReturnItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("qty", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("DAMAGED", "Damaged"),
                        ],
                        default="GOOD",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bardana_return_items",
                        to="authentication.organization",
                    ),
                ),
                (
                    "return_header",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="bardana.bardanareturnheader",
                    ),
                ),
                (
                    "bardana_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_items",
                        to="bardana.bardanatype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bardana Return Item",
                "verbose_name_plural": "Bardana Return Items",
                "db_table": "bardana_return_item",
            },
        ),
        migrations.CreateModel(
            name="BardanaIssueItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("qty", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "issue_header",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="bardana.bardanaissueheader",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bardana_issue_items",
                        to="authentication.organization",
                    ),
                ),
                (
                    "bardana_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issue_items",
                        to="bardana.bardanatype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bardana Issue Item",
                "verbose_name_plural": "Bardana Issue Items",
                "db_table": "bardana_issue_item",
            },
        ),
        migrations.AddIndex(
            model_name="bardanaissueheader",
            index=models.Index(
                fields=["organization", "date"], name="bardana_iss_organiz_daea2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bardanaissueheader",
            index=models.Index(
                fields=["organization", "party"], name="bardana_iss_organiz_77624c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bardanaissueheader",
            index=models.Index(
                fields=["organization", "status"], name="bardana_iss_organiz_3b3355_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bardanaissueheader",
            constraint=models.UniqueConstraint(
                fields=("organization", "voucher_no"),
                name="unique_organization_bardana_issue_no",
            ),
        ),
        migrations.AddIndex(
            model_name="bardanareturnheader",
            index=models.Index(
                fields=["organization", "date"], name="bardana_ret_organiz_e7e3c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bardanareturnheader",
            index=models.Index(
                fields=["organization", "party"], name="bardana_ret_organiz_93d308_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bardanareturnheader",
            index=models.Index(
                fields=["organization", "status"], name="bardana_ret_organiz_c685b7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bardanareturnheader",
            constraint=models.UniqueConstraint(
                fields=("organization", "voucher_no"),
                name="unique_organization_bardana_return_no",
            ),
        ),
        migrations.AddIndex(
            model_name="bardanatype",
            index=models.Index(
                fields=["organization", "is_active"],
                name="bardana_typ_organiz_d761b7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="bardanatype",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="unique_organization_bardana_code"
            ),
        ),
        migrations.AddIndex(
            model_name="bardanareturnitem",
            index=models.Index(
                fields=["organization"], name="bardana_ret_organiz_409b21_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bardanareturnitem",
            index=models.Index(
                fields=["return_header"], name="bardana_ret_return__fa4e39_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bardanaissueitem",
            index=models.Index(
                fields=["organization"], name="bardana_iss_organiz_464888_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bardanaissueitem",
            index=models.Index(
                fields=["issue_header"], name="bardana_iss_issue_h_a16a00_idx"
            ),
        ),
    ]
