# Generated by Django 5.2.10 on 2026-02-03 11:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(max_length=255)),
                ("name_hindi", models.CharField(blank=True, max_length=255, null=True)),
                ("level", models.PositiveSmallIntegerField(default=0)),
                (
                    "account_type",
                    models.CharField(
                        choices=[("GROUP", "Group"), ("ACCOUNT", "Account")],
                        default="ACCOUNT",
                        max_length=10,
                    ),
                ),
                (
                    "balance_nature",
                    models.CharField(
                        choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")],
                        default="DEBIT",
                        max_length=10,
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "debit_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "credit_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "closing_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "principal_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "interest_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "other_charges_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("pan_number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "aadhar_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("gst_number", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="authentication.organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="accounting.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "account",
                "verbose_name_plural": "accounts",
                "db_table": "accounting_account",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Daybook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "cash_opening_dr",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "cash_opening_cr",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "cash_receipts",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "cash_payments",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "cash_closing_dr",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "cash_closing_cr",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "bank_opening_dr",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "bank_opening_cr",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "bank_receipts",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "bank_payments",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "bank_closing_dr",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "bank_closing_cr",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_closed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daybooks",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "daybook",
                "verbose_name_plural": "daybooks",
                "db_table": "accounting_daybook",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DaybookTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("CR", "Cash Receipt"),
                            ("DR", "Cash Payment"),
                            ("JV", "Journal Voucher"),
                            ("CV", "Contra Voucher"),
                            ("BH", "Bank"),
                        ],
                        max_length=5,
                    ),
                ),
                ("voucher_number", models.CharField(db_index=True, max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("narration", models.TextField(blank=True, null=True)),
                ("is_bank_receipt", models.BooleanField(default=False)),
                (
                    "cheque_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("cheque_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credit_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_transactions",
                        to="accounting.account",
                    ),
                ),
                (
                    "daybook",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounting.daybook",
                    ),
                ),
                (
                    "debit_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="debit_transactions",
                        to="accounting.account",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daybook_transactions",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "daybook transaction",
                "verbose_name_plural": "daybook transactions",
                "db_table": "accounting_daybook_transaction",
                "ordering": ["-date", "-voucher_number"],
            },
        ),
        migrations.CreateModel(
            name="InterestCalculation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=15)),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "balance_type",
                    models.CharField(
                        choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")],
                        max_length=10,
                    ),
                ),
                ("is_posted", models.BooleanField(default=False)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_calculations",
                        to="accounting.account",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_calculations",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "interest calculation",
                "verbose_name_plural": "interest calculations",
                "db_table": "accounting_interest_calculation",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="InterestCalculationTemp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                ("days", models.PositiveIntegerField()),
                ("principal", models.DecimalField(decimal_places=2, max_digits=15)),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "calculated_interest",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "balance_type",
                    models.CharField(
                        choices=[("DEBIT", "Debit"), ("CREDIT", "Credit")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_calculation_temps",
                        to="accounting.account",
                    ),
                ),
                (
                    "calculation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temp_entries",
                        to="accounting.interestcalculation",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_calculation_temps",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "interest calculation temp",
                "verbose_name_plural": "interest calculation temps",
                "db_table": "accounting_interest_calculation_temp",
                "ordering": ["from_date"],
            },
        ),
        migrations.CreateModel(
            name="PartyBankDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bank_name", models.CharField(max_length=255)),
                (
                    "branch_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("account_number", models.CharField(max_length=50)),
                ("ifsc_code", models.CharField(max_length=20)),
                (
                    "account_holder_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_details",
                        to="accounting.account",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_bank_details",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "party bank detail",
                "verbose_name_plural": "party bank details",
                "db_table": "accounting_party_bank_details",
            },
        ),
        migrations.CreateModel(
            name="PartyLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serial_number", models.PositiveIntegerField(db_index=True)),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("CR", "Cash Receipt"),
                            ("DR", "Cash Payment"),
                            ("JV", "Journal Voucher"),
                            ("CV", "Contra Voucher"),
                            ("BH", "Bank"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "voucher_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("date", models.DateField(db_index=True)),
                ("narration", models.TextField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "principal_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "interest_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "other_charges",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "running_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "external_ref",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "external_ref_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="accounting.account",
                    ),
                ),
                (
                    "daybook_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="accounting.daybooktransaction",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_ledger_entries",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "party ledger entry",
                "verbose_name_plural": "party ledger entries",
                "db_table": "accounting_party_ledger",
                "ordering": ["-date", "-serial_number"],
            },
        ),
        migrations.AddField(
            model_name="interestcalculation",
            name="posted_ledger_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interest_calculation",
                to="accounting.partyledger",
            ),
        ),
        migrations.CreateModel(
            name="PartyLedgerOpening",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("financial_year", models.CharField(max_length=10)),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "principal_opening",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "interest_opening",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "other_charges_opening",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_balances",
                        to="accounting.account",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="party_ledger_openings",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "party ledger opening",
                "verbose_name_plural": "party ledger openings",
                "db_table": "accounting_party_ledger_opening",
            },
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["organization", "account_type"],
                name="accounting__organiz_da5c67_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["organization", "parent"], name="accounting__organiz_c3bcaf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="unique_organization_account_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="daybook",
            constraint=models.UniqueConstraint(
                fields=("organization", "date"), name="unique_organization_daybook_date"
            ),
        ),
        migrations.AddIndex(
            model_name="daybooktransaction",
            index=models.Index(
                fields=["organization", "date"], name="accounting__organiz_dcdf0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="daybooktransaction",
            index=models.Index(
                fields=["organization", "voucher_type", "date"],
                name="accounting__organiz_c2636b_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="partybankdetails",
            constraint=models.UniqueConstraint(
                fields=("account", "account_number"),
                name="unique_account_bank_account_number",
            ),
        ),
        migrations.AddIndex(
            model_name="partyledger",
            index=models.Index(
                fields=["organization", "date"], name="accounting__organiz_6555d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partyledger",
            index=models.Index(
                fields=["account", "date"], name="accounting__account_a50058_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="partyledger",
            constraint=models.UniqueConstraint(
                fields=("organization", "account", "serial_number"),
                name="unique_account_serial_number",
            ),
        ),
        migrations.AddIndex(
            model_name="interestcalculation",
            index=models.Index(
                fields=["organization", "date"], name="accounting__organiz_cc2b6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interestcalculation",
            index=models.Index(
                fields=["account", "is_posted"], name="accounting__account_9fc44b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="partyledgeropening",
            constraint=models.UniqueConstraint(
                fields=("organization", "account", "financial_year"),
                name="unique_account_financial_year_opening",
            ),
        ),
    ]
