# Generated by Django 5.2.10 on 2026-02-06 16:03

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
        ("authentication", "0002_organizationmembership_backdate_entry_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="calculate_interest_on_bardana",
            field=models.CharField(
                choices=[("DEFAULT", "Default"), ("YES", "Yes"), ("NO", "No")],
                default="DEFAULT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="charge_interest_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="depreciation_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="dr_limit",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="due_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="account",
            name="guarantor_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="guardian_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="guardian_relation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("S_O", "S/O"),
                    ("F_O", "F/O"),
                    ("W_O", "W/O"),
                    ("D_O", "D/O"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="party_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("KISAN", "Kisan"),
                    ("AARTI", "Aarti"),
                    ("STAFF", "Staff"),
                    ("LOADING_CONTRACTOR", "Loading Contractor"),
                    ("OTHERS", "Others"),
                    ("KISAN_D", "Kisan D"),
                    ("CHATAI_CONTRACTOR", "Chatai Contractor"),
                    ("MANDI", "Mandi"),
                    ("FINANCER", "Financer"),
                    ("GUARANTOR", "Guarantor"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="sauda_limit",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="account",
            name="tin_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="village",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="village_hindi",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["organization", "party_type"],
                name="accounting__organiz_39c286_idx",
            ),
        ),
    ]
