# Generated by Django 5.2.10 on 2026-02-03 15:24

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("inventory", "0002_room_is_sugar_free_room_occupancy_color_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftHeader",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "shift_no",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated: YYYY-NNNNN",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "remarks",
                    models.TextField(
                        blank=True, help_text="Reason for shift", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shift_headers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_room",
                    models.ForeignKey(
                        help_text="Source room",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts_from",
                        to="inventory.room",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_headers",
                        to="authentication.organization",
                    ),
                ),
                (
                    "to_room",
                    models.ForeignKey(
                        help_text="Destination room",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts_to",
                        to="inventory.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "shift header",
                "verbose_name_plural": "shift headers",
                "db_table": "warehouse_shift_header",
                "ordering": ["-date", "-shift_no"],
            },
        ),
        migrations.CreateModel(
            name="Shifting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_floor", models.PositiveIntegerField()),
                ("from_rack", models.PositiveIntegerField()),
                ("to_floor", models.PositiveIntegerField()),
                ("to_rack", models.PositiveIntegerField()),
                (
                    "quantity",
                    models.PositiveIntegerField(help_text="Number of bags shifted"),
                ),
                (
                    "narration",
                    models.TextField(
                        blank=True, help_text="Notes about this shift", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_records",
                        to="inventory.amad",
                    ),
                ),
                (
                    "from_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_items_from",
                        to="inventory.room",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shiftings",
                        to="authentication.organization",
                    ),
                ),
                (
                    "shift_header",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="warehouse.shiftheader",
                    ),
                ),
                (
                    "to_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shift_items_to",
                        to="inventory.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "shifting",
                "verbose_name_plural": "shiftings",
                "db_table": "warehouse_shifting",
                "ordering": ["shift_header", "id"],
            },
        ),
        migrations.CreateModel(
            name="TemperatureReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "floor_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional floor number (null for room-level reading)",
                        null=True,
                    ),
                ),
                ("reading_datetime", models.DateTimeField(db_index=True)),
                (
                    "low_temp",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum temperature recorded",
                        max_digits=5,
                    ),
                ),
                (
                    "high_temp",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum temperature recorded",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="NORMAL",
                        help_text="Computed status based on thresholds",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_temperature_readings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temperature_readings",
                        to="authentication.organization",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temperature_readings",
                        to="inventory.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "temperature reading",
                "verbose_name_plural": "temperature readings",
                "db_table": "warehouse_temperature_reading",
                "ordering": ["-reading_datetime"],
            },
        ),
        migrations.CreateModel(
            name="TemperatureThreshold",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_low",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        help_text="Target minimum temperature (e.g., 2°C)",
                        max_digits=5,
                    ),
                ),
                (
                    "target_high",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("4.00"),
                        help_text="Target maximum temperature (e.g., 4°C)",
                        max_digits=5,
                    ),
                ),
                (
                    "warning_deviation",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        help_text="Temperature deviation that triggers warning (default: 2°C)",
                        max_digits=5,
                    ),
                ),
                (
                    "critical_deviation",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Temperature deviation that triggers critical alert (default: 5°C)",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temperature_thresholds",
                        to="authentication.organization",
                    ),
                ),
                (
                    "room",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="temperature_threshold",
                        to="inventory.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "temperature threshold",
                "verbose_name_plural": "temperature thresholds",
                "db_table": "warehouse_temperature_threshold",
            },
        ),
        migrations.CreateModel(
            name="Unloading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("floor_number", models.PositiveIntegerField()),
                ("rack_number", models.PositiveIntegerField()),
                (
                    "quantity",
                    models.PositiveIntegerField(help_text="Number of bags unloaded"),
                ),
                (
                    "bill_type",
                    models.CharField(
                        choices=[
                            ("RENT", "Rent Bill"),
                            ("TRANSFER", "Stock Transfer"),
                            ("DAMAGE", "Damage/Loss"),
                            ("OTHER", "Other"),
                        ],
                        default="RENT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unloading_records",
                        to="inventory.amad",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_unloadings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unloadings",
                        to="authentication.organization",
                    ),
                ),
                (
                    "rent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dispatch/rent reference (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unloading_records",
                        to="inventory.rent",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unloading_records",
                        to="inventory.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "unloading",
                "verbose_name_plural": "unloadings",
                "db_table": "warehouse_unloading",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Loading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amad_no",
                    models.CharField(
                        db_index=True,
                        help_text="Denormalized amad number for quick lookup",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("floor_number", models.PositiveIntegerField()),
                ("rack_number", models.PositiveIntegerField()),
                (
                    "aisle",
                    models.PositiveIntegerField(
                        blank=True, help_text="Aisle/gali number (optional)", null=True
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(help_text="Number of bags loaded"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loading_records",
                        to="inventory.amad",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_loadings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loadings",
                        to="authentication.organization",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loading_records",
                        to="inventory.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "loading",
                "verbose_name_plural": "loadings",
                "db_table": "warehouse_loading",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "date"],
                        name="warehouse_l_organiz_94d454_idx",
                    ),
                    models.Index(
                        fields=["organization", "room", "floor_number", "rack_number"],
                        name="warehouse_l_organiz_f36929_idx",
                    ),
                    models.Index(
                        fields=["amad"], name="warehouse_l_amad_id_eaf3ae_idx"
                    ),
                    models.Index(
                        fields=["amad_no"], name="warehouse_l_amad_no_fa4fbb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MeterReading",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "reading_value",
                    models.DecimalField(
                        decimal_places=2, help_text="Meter reading value", max_digits=15
                    ),
                ),
                (
                    "photo_url",
                    models.CharField(
                        blank=True,
                        help_text="URL to photo of the reading",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_meter_readings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meter_readings",
                        to="authentication.organization",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        help_text="Room/machine reference",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meter_readings",
                        to="inventory.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "meter reading",
                "verbose_name_plural": "meter readings",
                "db_table": "warehouse_meter_reading",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["organization", "room", "date"],
                        name="warehouse_m_organiz_a218ed_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RackOccupancy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("floor_number", models.PositiveIntegerField()),
                ("rack_number", models.PositiveIntegerField()),
                (
                    "current_quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Current number of bags in this rack"
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rack_occupancies",
                        to="authentication.organization",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rack_occupancies",
                        to="inventory.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "rack occupancy",
                "verbose_name_plural": "rack occupancies",
                "db_table": "warehouse_rack_occupancy",
                "indexes": [
                    models.Index(
                        fields=["organization", "room"],
                        name="warehouse_r_organiz_dfc9a1_idx",
                    ),
                    models.Index(
                        fields=["organization", "room", "floor_number"],
                        name="warehouse_r_organiz_4adb5e_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "room", "floor_number", "rack_number"),
                        name="unique_org_room_floor_rack",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RoomFloor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "floor_number",
                    models.PositiveIntegerField(help_text="Floor number (1-N)"),
                ),
                (
                    "from_rack",
                    models.PositiveIntegerField(
                        help_text="Starting rack number on this floor"
                    ),
                ),
                (
                    "to_rack",
                    models.PositiveIntegerField(
                        help_text="Ending rack number on this floor"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_floors",
                        to="authentication.organization",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floor_configs",
                        to="inventory.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "room floor",
                "verbose_name_plural": "room floors",
                "db_table": "warehouse_room_floor",
                "ordering": ["room", "floor_number"],
                "indexes": [
                    models.Index(
                        fields=["organization", "room"],
                        name="warehouse_r_organiz_78d1fb_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "room", "floor_number"),
                        name="unique_org_room_floor",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="shiftheader",
            index=models.Index(
                fields=["organization", "date"], name="warehouse_s_organiz_da823d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shiftheader",
            constraint=models.UniqueConstraint(
                fields=("organization", "shift_no"), name="unique_org_shift_no"
            ),
        ),
        migrations.AddIndex(
            model_name="shifting",
            index=models.Index(
                fields=["organization"], name="warehouse_s_organiz_28fdd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shifting",
            index=models.Index(
                fields=["shift_header"], name="warehouse_s_shift_h_8b2045_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shifting",
            index=models.Index(fields=["amad"], name="warehouse_s_amad_id_949f7d_idx"),
        ),
        migrations.AddIndex(
            model_name="temperaturereading",
            index=models.Index(
                fields=["organization", "room", "reading_datetime"],
                name="warehouse_t_organiz_cb3fd3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="temperaturereading",
            index=models.Index(
                fields=["organization", "status"], name="warehouse_t_organiz_659b65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unloading",
            index=models.Index(
                fields=["organization", "date"], name="warehouse_u_organiz_020477_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unloading",
            index=models.Index(
                fields=["organization", "room", "floor_number", "rack_number"],
                name="warehouse_u_organiz_3cf69a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="unloading",
            index=models.Index(fields=["amad"], name="warehouse_u_amad_id_54be6e_idx"),
        ),
        migrations.AddIndex(
            model_name="unloading",
            index=models.Index(fields=["rent"], name="warehouse_u_rent_id_11f418_idx"),
        ),
    ]
