# Generated by Django 5.2.10 on 2026-02-05 18:45

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("authentication", "0002_organizationmembership_backdate_entry_limit_and_more"),
        ("inventory", "0003_add_room_temperature_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sauda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deal_no",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated: S/YYYY-NNNNN",
                        max_length=20,
                    ),
                ),
                ("deal_date", models.DateField(db_index=True)),
                ("variety", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total quantity in bags/packets",
                        max_digits=12,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Rate per unit",
                        max_digits=15,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total deal amount",
                        max_digits=15,
                    ),
                ),
                (
                    "due_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of days for delivery"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, help_text="Delivery due date", null=True
                    ),
                ),
                (
                    "dispatched_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Quantity already dispatched",
                        max_digits=12,
                    ),
                ),
                (
                    "balance_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Remaining quantity to be dispatched",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("PARTIAL", "Partially Dispatched"),
                            ("DISPATCHED", "Fully Dispatched"),
                            ("CANCELLED", "Cancelled"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="OPEN",
                        max_length=15,
                    ),
                ),
                ("payment_terms", models.TextField(blank=True, null=True)),
                (
                    "delivery_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        help_text="Buyer party account",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="saudas_as_buyer",
                        to="accounting.account",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_saudas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "commodity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="saudas",
                        to="inventory.commodity",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saudas",
                        to="authentication.organization",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        help_text="Seller party account",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="saudas_as_seller",
                        to="accounting.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "sauda",
                "verbose_name_plural": "saudas",
                "db_table": "trading_sauda",
                "ordering": ["-deal_date", "-deal_no"],
            },
        ),
        migrations.CreateModel(
            name="GatePass",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gp_no",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated: GP/YYYY-NNNNN",
                        max_length=20,
                    ),
                ),
                ("gp_date", models.DateField(db_index=True)),
                ("gp_time", models.TimeField(blank=True, null=True)),
                (
                    "transport_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("vehicle_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "driver_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "driver_contact",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "bilti_no",
                    models.CharField(
                        blank=True,
                        help_text="Transport receipt number",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("total_packets", models.PositiveIntegerField(default=0)),
                (
                    "total_weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total weight in kg",
                        max_digits=12,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("DONE", "Done"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gate_passes_as_buyer",
                        to="accounting.account",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_gate_passes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gate_passes",
                        to="authentication.organization",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gate_passes_as_seller",
                        to="accounting.account",
                    ),
                ),
                (
                    "sauda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gate_passes",
                        to="trading.sauda",
                    ),
                ),
            ],
            options={
                "verbose_name": "gate pass",
                "verbose_name_plural": "gate passes",
                "db_table": "trading_gate_pass",
                "ordering": ["-gp_date", "-gp_no"],
            },
        ),
        migrations.CreateModel(
            name="GatePassItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pkt1", models.PositiveIntegerField(default=0)),
                ("pkt2", models.PositiveIntegerField(default=0)),
                ("pkt3", models.PositiveIntegerField(default=0)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Weight in kg",
                        max_digits=12,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gate_pass_items",
                        to="inventory.amad",
                    ),
                ),
                (
                    "gate_pass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="trading.gatepass",
                    ),
                ),
            ],
            options={
                "verbose_name": "gate pass item",
                "verbose_name_plural": "gate pass items",
                "db_table": "trading_gate_pass_item",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["gate_pass"], name="trading_gat_gate_pa_efa3d3_idx"
                    ),
                    models.Index(
                        fields=["amad"], name="trading_gat_amad_id_52e042_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Katai",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "katai_no",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated: KT/YYYY-NNNNN",
                        max_length=20,
                    ),
                ),
                ("katai_date", models.DateField(db_index=True)),
                (
                    "bags_graded",
                    models.PositiveIntegerField(
                        default=0, help_text="Total bags graded"
                    ),
                ),
                (
                    "mota_bags",
                    models.PositiveIntegerField(
                        default=0, help_text="Mota (large) grade bags"
                    ),
                ),
                (
                    "chatta_bags",
                    models.PositiveIntegerField(
                        default=0, help_text="Chatta (flat) grade bags"
                    ),
                ),
                (
                    "beej_bags",
                    models.PositiveIntegerField(
                        default=0, help_text="Beej (seed) grade bags"
                    ),
                ),
                (
                    "mix_bags",
                    models.PositiveIntegerField(default=0, help_text="Mix grade bags"),
                ),
                (
                    "gulla_bags",
                    models.PositiveIntegerField(
                        default=0, help_text="Gulla grade bags"
                    ),
                ),
                (
                    "charge_per_bag",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_charges",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("labor_name", models.CharField(blank=True, max_length=255, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="katais",
                        to="inventory.amad",
                    ),
                ),
                (
                    "ledger_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="katai_entries",
                        to="accounting.partyledger",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="katais",
                        to="authentication.organization",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="katais",
                        to="accounting.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "katai",
                "verbose_name_plural": "katais",
                "db_table": "trading_katai",
                "ordering": ["-katai_date", "-katai_no"],
                "indexes": [
                    models.Index(
                        fields=["organization", "katai_date"],
                        name="trading_kat_organiz_173def_idx",
                    ),
                    models.Index(
                        fields=["organization", "party"],
                        name="trading_kat_organiz_e5141b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "katai_no"),
                        name="unique_organization_katai_no",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sauda",
            index=models.Index(
                fields=["organization", "deal_date"],
                name="trading_sau_organiz_e627bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sauda",
            index=models.Index(
                fields=["organization", "status"], name="trading_sau_organiz_a8a2f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sauda",
            index=models.Index(
                fields=["organization", "seller"], name="trading_sau_organiz_702f3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sauda",
            index=models.Index(
                fields=["organization", "buyer"], name="trading_sau_organiz_e0e23e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sauda",
            constraint=models.UniqueConstraint(
                fields=("organization", "deal_no"), name="unique_organization_deal_no"
            ),
        ),
        migrations.AddIndex(
            model_name="gatepass",
            index=models.Index(
                fields=["organization", "gp_date"],
                name="trading_gat_organiz_10edf6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gatepass",
            index=models.Index(
                fields=["organization", "status"], name="trading_gat_organiz_ccdc7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gatepass",
            index=models.Index(
                fields=["organization", "seller"], name="trading_gat_organiz_cc9b5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="gatepass",
            index=models.Index(
                fields=["organization", "buyer"], name="trading_gat_organiz_b4f6dc_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="gatepass",
            constraint=models.UniqueConstraint(
                fields=("organization", "gp_no"), name="unique_organization_gp_no"
            ),
        ),
    ]
