# Generated by Django 5.2.10 on 2026-02-03 18:05

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RentBillItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amad_no", models.CharField(max_length=20)),
                ("amad_date", models.DateField()),
                ("commodity_name", models.CharField(max_length=255)),
                ("party_name", models.CharField(max_length=255)),
                ("pkt1", models.PositiveIntegerField(default=0)),
                ("pkt2", models.PositiveIntegerField(default=0)),
                ("pkt3", models.PositiveIntegerField(default=0)),
                ("total_packets", models.PositiveIntegerField(default=0)),
                (
                    "weight_qtl",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Weight in quintals",
                        max_digits=12,
                    ),
                ),
                ("arrival_date", models.DateField()),
                ("dispatch_date", models.DateField(blank=True, null=True)),
                ("storage_days", models.PositiveIntegerField(default=0)),
                ("grace_days", models.PositiveIntegerField(default=0)),
                ("billable_days", models.PositiveIntegerField(default=0)),
                (
                    "rate_per_qtl",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Rent rate per quintal per month",
                        max_digits=10,
                    ),
                ),
                (
                    "rate_per_bag",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Rent rate per bag",
                        max_digits=10,
                    ),
                ),
                (
                    "rent_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rent Bill Item",
                "verbose_name_plural": "Rent Bill Items",
                "db_table": "billing_rent_bill_item",
                "ordering": ["amad_date", "amad_no"],
            },
        ),
        migrations.CreateModel(
            name="PriceBreakup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        choices=[
                            ("RENT", "Storage Rent"),
                            ("LOADING", "Loading Charges"),
                            ("UNLOADING", "Unloading Charges"),
                            ("DALA", "Dala Charges"),
                            ("KATAI", "Katai Charges"),
                            ("INSURANCE", "Insurance"),
                            ("RELOAD", "Reload Charges"),
                            ("DUMP", "Dump Charges"),
                            ("OTHER", "Other Charges"),
                        ],
                        max_length=20,
                    ),
                ),
                ("hsn_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_breakups",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Breakup",
                "verbose_name_plural": "Price Breakups",
                "db_table": "billing_price_breakup",
                "ordering": ["component"],
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "receipt_no",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated: RV/YYYY-NNNNN",
                        max_length=20,
                    ),
                ),
                ("receipt_date", models.DateField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "amount_in_words",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CHEQUE", "Cheque"),
                            ("BANK", "Bank Transfer"),
                            ("UPI", "UPI"),
                        ],
                        default="CASH",
                        max_length=10,
                    ),
                ),
                ("cheque_no", models.CharField(blank=True, max_length=50, null=True)),
                ("cheque_date", models.DateField(blank=True, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "branch_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "is_pdc",
                    models.BooleanField(
                        default=False, help_text="Is Post Dated Cheque?"
                    ),
                ),
                (
                    "is_cleared",
                    models.BooleanField(
                        default=True, help_text="Has the cheque cleared?"
                    ),
                ),
                (
                    "bank_ref_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("upi_ref_no", models.CharField(blank=True, max_length=100, null=True)),
                ("narration", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CONFIRMED", "Confirmed"),
                            ("PARTIAL_PAID", "Partially Paid"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ledger_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipt_entries",
                        to="accounting.partyledger",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="authentication.organization",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="accounting.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receipt",
                "verbose_name_plural": "Receipts",
                "db_table": "billing_receipt",
                "ordering": ["-receipt_date", "-receipt_no"],
            },
        ),
        migrations.CreateModel(
            name="ReceiptAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt_allocations",
                        to="authentication.organization",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="billing.receipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receipt Allocation",
                "verbose_name_plural": "Receipt Allocations",
                "db_table": "billing_receipt_allocation",
            },
        ),
        migrations.CreateModel(
            name="RentBillHeader",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bill_no",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated: KB/YYYY-NNNNN",
                        max_length=20,
                    ),
                ),
                ("bill_date", models.DateField(db_index=True)),
                ("party_name", models.CharField(max_length=255)),
                ("party_gstin", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "party_state",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "rent_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total storage rent",
                        max_digits=15,
                    ),
                ),
                (
                    "loading_charges",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "unloading_charges",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "dala_charges",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "katai_charges",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "insurance_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "reload_charges",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "dump_charges",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "other_charges",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "taxable_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total before GST",
                        max_digits=15,
                    ),
                ),
                (
                    "gst_type",
                    models.CharField(
                        choices=[
                            ("INTRA", "Intra-State (CGST + SGST)"),
                            ("INTER", "Inter-State (IGST)"),
                        ],
                        default="INTRA",
                        max_length=10,
                    ),
                ),
                (
                    "cgst_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "sgst_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "igst_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "igst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_gst",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "tds_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "tds_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Taxable + GST",
                        max_digits=15,
                    ),
                ),
                (
                    "round_off",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total after rounding",
                        max_digits=15,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "balance_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("CONFIRMED", "Confirmed"),
                            ("PARTIAL_PAID", "Partially Paid"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_rent_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_rent_bills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rent Bill",
                "verbose_name_plural": "Rent Bills",
                "db_table": "billing_rent_bill_header",
                "ordering": ["-bill_date", "-bill_no"],
            },
        ),
    ]
