# Generated by Django 5.2.10 on 2026-02-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("authentication", "0001_initial"),
        ("billing", "0001_initial"),
        ("inventory", "0003_add_room_temperature_fields"),
        ("masters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rentbillheader",
            name="gst_rate",
            field=models.ForeignKey(
                blank=True,
                help_text="GST rate applied",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rent_bills",
                to="masters.gstrate",
            ),
        ),
        migrations.AddField(
            model_name="rentbillheader",
            name="ledger_entry",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated ledger entry",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rent_bill_entries",
                to="accounting.partyledger",
            ),
        ),
        migrations.AddField(
            model_name="rentbillheader",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rent_bills",
                to="authentication.organization",
            ),
        ),
        migrations.AddField(
            model_name="rentbillheader",
            name="party",
            field=models.ForeignKey(
                help_text="Party account",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rent_bills",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="receiptallocation",
            name="rent_bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipt_allocations",
                to="billing.rentbillheader",
            ),
        ),
        migrations.AddField(
            model_name="pricebreakup",
            name="rent_bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="breakups",
                to="billing.rentbillheader",
            ),
        ),
        migrations.AddField(
            model_name="rentbillitem",
            name="amad",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bill_items",
                to="inventory.amad",
            ),
        ),
        migrations.AddField(
            model_name="rentbillitem",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rent_bill_items",
                to="authentication.organization",
            ),
        ),
        migrations.AddField(
            model_name="rentbillitem",
            name="rent_bill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="billing.rentbillheader",
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["organization", "receipt_date"],
                name="billing_rec_organiz_f82a74_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["organization", "party"], name="billing_rec_organiz_9e85a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["organization", "status"], name="billing_rec_organiz_176060_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="receipt",
            constraint=models.UniqueConstraint(
                fields=("organization", "receipt_no"),
                name="unique_organization_receipt_no",
            ),
        ),
        migrations.AddIndex(
            model_name="rentbillheader",
            index=models.Index(
                fields=["organization", "bill_date"],
                name="billing_ren_organiz_34ed49_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rentbillheader",
            index=models.Index(
                fields=["organization", "party"], name="billing_ren_organiz_766c3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentbillheader",
            index=models.Index(
                fields=["organization", "status"], name="billing_ren_organiz_8802e8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rentbillheader",
            constraint=models.UniqueConstraint(
                fields=("organization", "bill_no"), name="unique_organization_bill_no"
            ),
        ),
        migrations.AddIndex(
            model_name="receiptallocation",
            index=models.Index(
                fields=["organization"], name="billing_rec_organiz_6d4504_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receiptallocation",
            index=models.Index(
                fields=["receipt"], name="billing_rec_receipt_aa58a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receiptallocation",
            index=models.Index(
                fields=["rent_bill"], name="billing_rec_rent_bi_f92039_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="receiptallocation",
            constraint=models.UniqueConstraint(
                fields=("receipt", "rent_bill"), name="unique_receipt_bill_allocation"
            ),
        ),
        migrations.AddIndex(
            model_name="pricebreakup",
            index=models.Index(
                fields=["organization"], name="billing_pri_organiz_1da5ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricebreakup",
            index=models.Index(
                fields=["rent_bill"], name="billing_pri_rent_bi_fd51dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentbillitem",
            index=models.Index(
                fields=["organization"], name="billing_ren_organiz_ac0bb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentbillitem",
            index=models.Index(
                fields=["rent_bill"], name="billing_ren_rent_bi_52e2b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rentbillitem",
            index=models.Index(fields=["amad"], name="billing_ren_amad_id_088d7e_idx"),
        ),
    ]
