# Generated by Django 5.2.10 on 2026-02-06 05:03

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0002_organizationmembership_backdate_entry_limit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Allowance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed Amount"),
                            ("PERCENTAGE", "Percentage of Basic"),
                        ],
                        default="FIXED",
                        max_length=15,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Fixed amount or percentage value",
                        max_digits=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowances",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allowance",
                "verbose_name_plural": "Allowances",
                "db_table": "payroll_allowance",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("employee_name", models.CharField(max_length=255)),
                ("month", models.PositiveIntegerField()),
                ("year", models.PositiveIntegerField()),
                ("month_days", models.PositiveIntegerField(default=30)),
                (
                    "present_days",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "lwp",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        help_text="Leave Without Pay",
                        max_digits=5,
                    ),
                ),
                (
                    "cl",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        help_text="Casual Leave",
                        max_digits=5,
                    ),
                ),
                (
                    "ml",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        help_text="Medical Leave",
                        max_digits=5,
                    ),
                ),
                (
                    "el",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        help_text="Earned Leave",
                        max_digits=5,
                    ),
                ),
                (
                    "metl",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        help_text="Maternity Leave",
                        max_digits=5,
                    ),
                ),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "gross_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_allowances",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total_deductions",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "pf_employee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "pf_employer",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "esi_employee",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "esi_employer",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "loan_emi",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PROCESSED", "Processed"),
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendance Records",
                "db_table": "payroll_attendance",
                "ordering": ["-year", "-month", "employee_name"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceAllowance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "allowance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_items",
                        to="payroll.allowance",
                    ),
                ),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowance_items",
                        to="payroll.attendance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Allowance",
                "verbose_name_plural": "Attendance Allowances",
                "db_table": "payroll_attendance_allowance",
            },
        ),
        migrations.CreateModel(
            name="DailyWage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("worker_name", models.CharField(max_length=255)),
                ("work_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_wages",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Wage",
                "verbose_name_plural": "Daily Wages",
                "db_table": "payroll_daily_wage",
                "ordering": ["-date", "worker_name"],
            },
        ),
        migrations.CreateModel(
            name="Deduction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("FIXED", "Fixed Amount"),
                            ("PERCENTAGE", "Percentage of Basic"),
                        ],
                        default="FIXED",
                        max_length=15,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Fixed amount or percentage value",
                        max_digits=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deductions",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Deduction",
                "verbose_name_plural": "Deductions",
                "db_table": "payroll_deduction",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceDeduction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deduction_items",
                        to="payroll.attendance",
                    ),
                ),
                (
                    "deduction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_items",
                        to="payroll.deduction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Deduction",
                "verbose_name_plural": "Attendance Deductions",
                "db_table": "payroll_attendance_deduction",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated: EMP/YYYY-NNNNN",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("aadhaar", models.CharField(blank=True, max_length=20, null=True)),
                ("pan_number", models.CharField(blank=True, max_length=20, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bank_account_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("bank_ifsc", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "bank_branch",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "uan",
                    models.CharField(
                        blank=True,
                        help_text="Universal Account Number for PF",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("pf_applicable", models.BooleanField(default=False)),
                ("esi_applicable", models.BooleanField(default=False)),
                ("joining_date", models.DateField(blank=True, null=True)),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ON_LEAVE", "On Leave"),
                            ("INACTIVE", "Inactive"),
                            ("PROBATION", "Probation"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "db_table": "payroll_employee",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="attendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_records",
                to="payroll.employee",
            ),
        ),
        migrations.CreateModel(
            name="EmployeeAllowance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Override value for this employee",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "allowance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_allowances",
                        to="payroll.allowance",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowances",
                        to="payroll.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Allowance",
                "verbose_name_plural": "Employee Allowances",
                "db_table": "payroll_employee_allowance",
            },
        ),
        migrations.CreateModel(
            name="EmployeeDeduction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Override value for this employee",
                        max_digits=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deduction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_deductions",
                        to="payroll.deduction",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deductions",
                        to="payroll.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Deduction",
                "verbose_name_plural": "Employee Deductions",
                "db_table": "payroll_employee_deduction",
            },
        ),
        migrations.CreateModel(
            name="PayPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "post_no",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated: PP/YYYY-NNNNN",
                        max_length=20,
                    ),
                ),
                ("post_name", models.CharField(max_length=255)),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "cl_entitlement",
                    models.PositiveIntegerField(
                        default=0, help_text="Casual Leave per year"
                    ),
                ),
                (
                    "el_entitlement",
                    models.PositiveIntegerField(
                        default=0, help_text="Earned Leave per year"
                    ),
                ),
                (
                    "ml_entitlement",
                    models.PositiveIntegerField(
                        default=0, help_text="Medical Leave per year"
                    ),
                ),
                (
                    "metl_entitlement",
                    models.PositiveIntegerField(
                        default=0, help_text="Maternity Leave per year"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pay_posts",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pay Post",
                "verbose_name_plural": "Pay Posts",
                "db_table": "payroll_pay_post",
                "ordering": ["post_name"],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="pay_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="payroll.paypost",
            ),
        ),
        migrations.CreateModel(
            name="PayrollLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("employee_name", models.CharField(max_length=255)),
                ("serial_number", models.PositiveIntegerField()),
                ("transaction_date", models.DateField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("SAL", "Salary"),
                            ("ADV", "Advance"),
                            ("LOAN", "Loan"),
                            ("EMI", "EMI Deduction"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "running_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "reference_id",
                    models.UUIDField(
                        blank=True, help_text="Reference to attendance/loan", null=True
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_ledger",
                        to="payroll.employee",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_ledger",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payroll Ledger Entry",
                "verbose_name_plural": "Payroll Ledger Entries",
                "db_table": "payroll_ledger",
                "ordering": ["employee", "serial_number"],
            },
        ),
        migrations.CreateModel(
            name="SalaryIncrement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_date", models.DateField()),
                (
                    "to_date",
                    models.DateField(
                        blank=True, help_text="Null means currently active", null=True
                    ),
                ),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "pf_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Salary for PF calculation",
                        max_digits=12,
                    ),
                ),
                (
                    "esi_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Salary for ESI calculation",
                        max_digits=12,
                    ),
                ),
                (
                    "pf_employee_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("12.00"), max_digits=5
                    ),
                ),
                (
                    "pf_employer_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("12.00"), max_digits=5
                    ),
                ),
                (
                    "esi_employee_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.75"), max_digits=5
                    ),
                ),
                (
                    "esi_employer_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("3.25"), max_digits=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_increments",
                        to="payroll.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salary Increment",
                "verbose_name_plural": "Salary Increments",
                "db_table": "payroll_salary_increment",
                "ordering": ["-from_date"],
            },
        ),
        migrations.CreateModel(
            name="StaffLoan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "loan_no",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated: SL/YYYY-NNNNN",
                        max_length=20,
                    ),
                ),
                ("employee_name", models.CharField(max_length=255)),
                ("loan_date", models.DateField()),
                (
                    "loan_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "emi",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "repaid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("REPAID", "Repaid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_staff_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_staff_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="staff_loans",
                        to="payroll.employee",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_loans",
                        to="authentication.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Loan",
                "verbose_name_plural": "Staff Loans",
                "db_table": "payroll_staff_loan",
                "ordering": ["-loan_date", "-loan_no"],
            },
        ),
        migrations.AddConstraint(
            model_name="allowance",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="unique_org_allowance_code"
            ),
        ),
        migrations.AddIndex(
            model_name="dailywage",
            index=models.Index(
                fields=["organization", "date"], name="payroll_dai_organiz_309f6a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="deduction",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="unique_org_deduction_code"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["organization", "year", "month"],
                name="payroll_att_organiz_910790_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["organization", "status"], name="payroll_att_organiz_a5a75f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("organization", "employee", "month", "year"),
                name="unique_org_employee_month_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeallowance",
            constraint=models.UniqueConstraint(
                fields=("employee", "allowance"), name="unique_employee_allowance"
            ),
        ),
        migrations.AddConstraint(
            model_name="employeededuction",
            constraint=models.UniqueConstraint(
                fields=("employee", "deduction"), name="unique_employee_deduction"
            ),
        ),
        migrations.AddConstraint(
            model_name="paypost",
            constraint=models.UniqueConstraint(
                fields=("organization", "post_no"), name="unique_org_post_no"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["organization", "status"], name="payroll_emp_organiz_0cf8b8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="employee",
            constraint=models.UniqueConstraint(
                fields=("organization", "employee_code"),
                name="unique_org_employee_code",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollledger",
            index=models.Index(
                fields=["organization", "employee"],
                name="payroll_led_organiz_c6b1a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollledger",
            index=models.Index(
                fields=["organization", "transaction_date"],
                name="payroll_led_organiz_d099be_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="staffloan",
            index=models.Index(
                fields=["organization", "employee"],
                name="payroll_sta_organiz_929066_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="staffloan",
            index=models.Index(
                fields=["organization", "status"], name="payroll_sta_organiz_d7f50b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="staffloan",
            constraint=models.UniqueConstraint(
                fields=("organization", "loan_no"), name="unique_org_staff_loan_no"
            ),
        ),
    ]
