# Generated by Django 5.2.10 on 2026-02-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmembership",
            name="backdate_entry_limit",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Number of days allowed for backdated entries",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="loan_per_bag_limit",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="organizationmembership",
            name="permissions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
