# Generated by Django 5.2.10 on 2026-02-05 19:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0001_initial"),
        ("authentication", "0002_organizationmembership_backdate_entry_limit_and_more"),
        ("inventory", "0003_add_room_temperature_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Advance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "advance_no",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated: ADV/YYYY-NNNNN",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "expected_date",
                    models.DateField(
                        blank=True,
                        help_text="Expected date of goods arrival",
                        null=True,
                    ),
                ),
                (
                    "party_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized party name for quick display",
                        max_length=255,
                    ),
                ),
                (
                    "bags",
                    models.PositiveIntegerField(
                        default=0, help_text="Expected bags from the party"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CHEQUE", "Cheque"),
                            ("BANK", "Bank Transfer"),
                            ("UPI", "UPI"),
                        ],
                        default="CASH",
                        max_length=10,
                    ),
                ),
                (
                    "cheque_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("cheque_date", models.DateField(blank=True, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "upi_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "bardana_voucher",
                    models.CharField(
                        blank=True,
                        help_text="Bardana (packaging) voucher reference",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("narration", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ADJUSTED", "Adjusted"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
                (
                    "adjusted_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "balance_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_advances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ledger_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advance_entries",
                        to="accounting.partyledger",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advances",
                        to="authentication.organization",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        help_text="Farmer/party receiving advance",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advances",
                        to="accounting.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "advance",
                "verbose_name_plural": "advances",
                "db_table": "loans_advance",
                "ordering": ["-date", "-advance_no"],
                "indexes": [
                    models.Index(
                        fields=["organization", "date"],
                        name="loans_advan_organiz_a849b6_idx",
                    ),
                    models.Index(
                        fields=["organization", "party"],
                        name="loans_advan_organiz_7b98bc_idx",
                    ),
                    models.Index(
                        fields=["organization", "status"],
                        name="loans_advan_organiz_0dd711_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "advance_no"),
                        name="unique_organization_advance_no",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LoanAgainstGoods",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "loan_no",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated: LN/YYYY-NNNNN",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "party_name",
                    models.CharField(
                        blank=True, help_text="Denormalized party name", max_length=255
                    ),
                ),
                (
                    "amad_no",
                    models.CharField(
                        blank=True, help_text="Denormalized amad number", max_length=20
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.50"),
                        help_text="Monthly interest rate percentage",
                        max_digits=5,
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CHEQUE", "Cheque"),
                            ("BANK", "Bank Transfer"),
                            ("UPI", "UPI"),
                        ],
                        default="CASH",
                        max_length=10,
                    ),
                ),
                (
                    "cheque_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("cheque_date", models.DateField(blank=True, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "upi_reference",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("narration", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PARTIAL", "Partially Repaid"),
                            ("REPAID", "Repaid"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
                (
                    "repaid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "balance_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                (
                    "accrued_interest",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amad",
                    models.ForeignKey(
                        help_text="Amad (stored goods) used as collateral",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="inventory.amad",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ledger_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loan_entries",
                        to="accounting.partyledger",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans_against_goods",
                        to="authentication.organization",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        help_text="Party taking the loan",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans_against_goods",
                        to="accounting.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "loan against goods",
                "verbose_name_plural": "loans against goods",
                "db_table": "loans_loan_against_goods",
                "ordering": ["-date", "-loan_no"],
                "indexes": [
                    models.Index(
                        fields=["organization", "date"],
                        name="loans_loan__organiz_96734c_idx",
                    ),
                    models.Index(
                        fields=["organization", "party"],
                        name="loans_loan__organiz_4bd2e5_idx",
                    ),
                    models.Index(
                        fields=["organization", "status"],
                        name="loans_loan__organiz_7ad10e_idx",
                    ),
                    models.Index(
                        fields=["organization", "amad"],
                        name="loans_loan__organiz_d7e136_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "loan_no"),
                        name="unique_organization_loan_no",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LoanLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serial_number", models.PositiveIntegerField(db_index=True)),
                ("date", models.DateField(db_index=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("DR", "Debit"), ("CR", "Credit")], max_length=5
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "running_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=15
                    ),
                ),
                ("amad_no", models.CharField(blank=True, max_length=20, null=True)),
                ("narration", models.TextField(blank=True, null=True)),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="ADVANCE, LOAN, or INTEREST",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("reference_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loan_ledger_entries",
                        to="inventory.amad",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_ledger_entries",
                        to="authentication.organization",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_ledger_entries",
                        to="accounting.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "loan ledger entry",
                "verbose_name_plural": "loan ledger entries",
                "db_table": "loans_loan_ledger",
                "ordering": ["-date", "-serial_number"],
                "indexes": [
                    models.Index(
                        fields=["organization", "date"],
                        name="loans_loan__organiz_c08443_idx",
                    ),
                    models.Index(
                        fields=["party", "date"], name="loans_loan__party_i_cae6b8_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "party", "serial_number"),
                        name="unique_loan_ledger_serial",
                    )
                ],
            },
        ),
    ]
